apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast-client
  template:
    metadata:
      labels:
        app: hazelcast-client
    spec:
      containers:
      - name: hazelcast-client
        image: quay.io/rhn_support_sreber/go-hazelcast:latest
        env:
        - name: HAZELCAST_SERVICE
          value: "hazelcast-service.project-100.svc.cluster.local:5701"  # Update to match your Hazelcast service name
        - name: HAZELCAST_MAP_NAME
          value: "example-map"  # Specify your map name here
      restartPolicy: Always

