apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast-client
  template:
    metadata:
      labels:
        app: hazelcast-client
    spec:
      containers:
      - name: hazelcast-client
        image: quay.io/rhn_support_sreber/go-hazelcast:latest
        env:
        - name: HAZELCAST_SERVICE
          value: "hazelcast.project-100.svc.cluster.local:5701"
        - name: HAZELCAST_MAP_NAME
          value: "example-map"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always

